/**
 * UTXO Referee - BitVM3 Module
 *
 * V2 verifies signed state, exact settlement transactions, secret-safe BitVM
 * traces, and a NUMS-keyed optimistic assertion graph.
 *
 * Usage:
 *   const referee = require('./bitvm3/utxo_referee');
 *
 *   const { settlement, trace, assertionGraph } = referee.v2;
 *
 * The historical sweep API is available only through:
 *   referee.legacyUnsafe.load({ acknowledgeUnsafePrototype: true })
 */

const types = require('./types');
const merkle = require('./merkle');
const verify = require('./verify');
const circuit = require('./circuit');
const m1Spec = require('./m1_spec');
const m1ReceiptLedger = require('./m1_receipt_ledger');
const m1DepositIndexer = require('./m1_deposit_indexer');
const m1Transition = require('./m1_transition');
const m1TransitionCircuit = require('./m1_transition_circuit');
const m1TallyMap = require('./m1_tally_map');
const m1ChallengeWitness = require('./m1_challenge_witness');
const m1OracleDeltaPublication = require('./m1_oracle_delta_publication');
const m1WitnessDelta = require('./m1_witness_delta');
const m1RoutingCommitments = require('./m1_routing_commitments');
const m1ChainEnv = require('./m1_chain_env');
const m1ProceduralSync = require('./m1_procedural_sync');
const m1Pipeline = require('./m1_pipeline');
const m1ParallelUtxoIndex = require('./m1_parallel_utxo_index');
const m1BitvmSearchManifolds = require('./m1_bitvm_search_manifolds');
const jurassicBitvmMechanisms = require('./jurassic_bitvm_mechanisms');
const halalCapitalTemplateRegistry = require('./halal_capital_template_registry');
const halalCapitalMarketplaceDemo = require('./halal_capital_marketplace_demo');
const halalCapitalTradeLayerTokens = require('./halal_capital_tradelayer_tokens');
const halalCapitalProtocolBundles = require('./halal_capital_protocol_bundles');
const omaniFiqhStablecoinCompliance = require('./omani_fiqh_stablecoin_compliance');
const sukukStablecoinHalalDefi = require('./sukuk_stablecoin_halal_defi');
const lightningIntegration = require('./lightning_integration');
const spiralLdkValueAdd = require('./spiral_ldk_value_add');
const lightningLiquidityLease = require('./lightning_liquidity_lease');
const lightningWalletIntegration = require('./lightning_wallet_integration');
const lightningTaprootAssetsStablecoin = require('./lightning_taproot_assets_stablecoin');
const lightningArkLiquidityGraft = require('./lightning_ark_liquidity_graft');
const arkTaprootMiniscriptProofManifest = require('./ark_taproot_miniscript_proof_manifest');
const arkZkMiniscriptProof = require('./ark_zk_miniscript_proof');
const lightningZkPrograms = require('./shinigami/lightning_zk_programs');
const shinigamiProofPublication = require('./shinigami/shinigami_proof_publication');
const shinigamiVirtualCetArk = require('./shinigami/shinigami_virtual_cet_ark');
const shinigamiVirtualCetProofCorpus = require('./shinigami/shinigami_virtual_cet_proof_corpus');
const dlcTokenizerSecurityComparison = require('./shinigami/dlc_tokenizer_security_comparison');
const aspBitvmReserveBond = require('./asp_bitvm_reserve_bond');
const arkDlcSettlement = require('./ark_dlc_settlement');
const arkLiquidityGraftManager = require('./ark_liquidity_graft_manager');
const lnbtcTlusdLiquidityPatch = require('./lnbtc_tlusd_liquidity_patch');
const bitvmChannelRouter = require('./bitvm_channel_router');
const lightningTradeLayerOracleDlc = require('./lightning_tradelayer_oracle_dlc');
const tradeLayerPnlRouteAdapter = require('./tradelayer_pnl_route_adapter');
const tradeLayerPnlStateNetting = require('./tradelayer_pnl_state_netting');
const tradeLayerSendOracleExtractor = require('./tradelayer_send_oracle_extractor');
const tradeLayerSendSweepPsbt = require('./tradelayer_send_sweep_psbt');
const tradeLayerSendFraudChallenges = require('./tradelayer_send_fraud_challenges');
const tradeLayerSendFlowModel = require('./tradelayer_send_flow_model');
const tradeLayerSendPolicy = require('./tradelayer_send_policy');
const tradeLayerSendRpcSweep = require('./tradelayer_send_rpc_sweep');
const tradeLayerSendWatchtower = require('./tradelayer_send_watchtower');
const tradeLayerStateCheckpointReferee = require('./tradelayer_state_checkpoint_referee');
const tradeLayerWithdrawalQueueReferee = require('./tradelayer_withdrawal_queue_referee');
const tradeLayerReserveReconciliationReferee = require('./tradelayer_reserve_reconciliation_referee');
const tradeLayerLiveReserveAdapter = require('./tradelayer_live_reserve_adapter');
const tradeLayerDlcCetOracleSelection = require('./tradelayer_dlc_cet_oracle_selection');
const tradeLayerDlcAdaptorSig = require('./tradelayer_dlc_adaptor_sig');
const tradeLayerTaproot = require('./tradelayer_taproot');
const tradeLayerMusig2 = require('./legacy/tradelayer_musig2');
const tradeLayerTaprootScript = require('./tradelayer_taproot_script');
const taprootReserveVault = require('./taproot_reserve_vault');
const tradeLayerRbtcHourlyAutoRoll = require('./tradelayer_rbtc_hourly_autoroll');
const tradeLayerTx30RelayAnchor = require('./tradelayer_tx30_relay_anchor');
const tradeLayerTx30RelayRetrieval = require('./tradelayer_tx30_relay_retrieval');
const tradeLayerBetaGatePackage = require('./tradelayer_beta_gate_package');
const tradeLayerBitvmGadgets = require('./tradelayer_bitvm_gadgets');
const tradeLayerBitvmCircuit = require('./tradelayer_bitvm_circuit');
const tradeLayerBitvmComparator = require('./tradelayer_bitvm_comparator');
const tradeLayerTaprootTree = require('./tradelayer_taproot_tree');
const tradeLayerBitvmDispute = require('./tradelayer_bitvm_dispute');
const tradeLayerBitvmSolvencyReferee = require('./tradelayer_bitvm_solvency_referee');
const tradeLayerBitvmSha256 = require('./tradelayer_bitvm_sha256');
const tradeLayerPerpPnlReferee = require('./tradelayer_perp_pnl_referee');
const bitvmLiquidityLeaseReferee = require('./bitvm_liquidity_lease_referee');
const bitvmArenaSecurityReport = require('./bitvm_arena_security_report');
const tradeLayerBitvmStack = require('./tradelayer_bitvm_stack');
const tradeLayerUtxoRefLivePath = require('./tradelayer_utxoref_live_path');
const rbtcDlcZkSettlementAdapter = require('./rbtc_dlc_zk_settlement_adapter');
const utxoRefV2 = require('./utxoref_v2');
const bitvmTraceV2 = require('./bitvm_trace_v2');
const bitvmAssertionGraphV2 = require('./bitvm_assertion_graph_v2');
const dlcCanonicalJson = require('./dlc_canonical_json');
const dlcContractState = require('./dlc_contract_state');
const dlcThresholdOracle = require('./dlc_threshold_oracle');
const { DlcStateStore } = require('./dlc_state_store');
const dlcCryptoProvider = require('./dlc_crypto_provider');
const { DlcOracleEventStore } = require('./dlc_oracle_event_store');
const { DlcSigningAuthorizationStore } = require('./dlc_signing_authorization_store');
const { DlcRefundRecoveryStore } = require('./dlc_refund_recovery_store');
const dlcNativeSignerProcessClient = require('./dlc_native_signer_process_client');
const dlcTransactionValidator = require('./dlc_transaction_validator');
const dlcSignatureValidator = require('./dlc_signature_validator');
const dlcChainGuard = require('./dlc_chain_guard');
const dlcBitcoinCoreObserver = require('./dlc_bitcoin_core_observer');
const dlcPeerTranscript = require('./dlc_peer_transcript');
const { DlcPeerSessionStore } = require('./dlc_peer_session_store');
const { DlcWatchtowerJournal } = require('./dlc_watchtower_journal');
const dlcAnchorRecoveryGuard = require('./dlc_anchor_recovery_guard');
const dlcFundingPrebroadcastGuard = require('./dlc_funding_prebroadcast_guard');
const dlcExecutionPrebroadcastGuard = require('./dlc_execution_prebroadcast_guard');
const { DlcBroadcastAuthorizationStore } = require('./dlc_broadcast_authorization_store');
const dlcJournalCheckpoint = require('./dlc_journal_checkpoint');

module.exports = {
  // Types
  CommitmentPackage: types.CommitmentPackage,
  PayoutLeaf: types.PayoutLeaf,
  PayoutOutput: types.PayoutOutput,
  ResidualOutput: types.ResidualOutput,
  SweepObject: types.SweepObject,
  LEAF_TAG: types.LEAF_TAG,

  // Serialization helpers
  writeU64LE: types.writeU64LE,
  readU64LE: types.readU64LE,
  serializeScriptPubKey: types.serializeScriptPubKey,

  // Merkle tree
  PayoutMerkleTree: merkle.PayoutMerkleTree,
  computeWithdrawalRoot: merkle.computeWithdrawalRoot,
  buildTreeWithProofs: merkle.buildTreeWithProofs,
  ZERO_HASH: merkle.ZERO_HASH,

  // Verification
  verifySweep: verify.verifySweep,
  verifyRules: verify.verifyRules,
  deriveSettlementRouting: verify.deriveSettlementRouting,
  verifySettlementRouting: verify.verifySettlementRouting,

  // Circuit
  RefereeCircuit: circuit.RefereeCircuit,
  generateRefereeCircuit: circuit.generateRefereeCircuit,
  toCircuitWitness: circuit.toCircuitWitness,

  // Milestone 1 spec helpers
  PAYOUT_LEAF_SCHEMA_FIELDS: m1Spec.PAYOUT_LEAF_SCHEMA_FIELDS,
  COMMITMENT_PACKAGE_SCHEMA_FIELDS: m1Spec.COMMITMENT_PACKAGE_SCHEMA_FIELDS,
  RECEIPT_DLC_TEMPLATE_V1: m1Spec.RECEIPT_DLC_TEMPLATE_V1,
  buildReceiptDlcTemplate: m1Spec.buildReceiptDlcTemplate,
  normalizeEpochId: m1Spec.normalizeEpochId,
  normalizeAmountSats: m1Spec.normalizeAmountSats,
  validatePayoutLeafRecord: m1Spec.validatePayoutLeafRecord,
  validateCommitmentPackageRecord: m1Spec.validateCommitmentPackageRecord,
  templateHashHex: m1Spec.templateHashHex,
  ReceiptLedger: m1ReceiptLedger.ReceiptLedger,
  ReceiptDepositIndexer: m1DepositIndexer.ReceiptDepositIndexer,
  DEPOSIT_STATUSES: m1DepositIndexer.DEPOSIT_STATUSES,
  computeConfirmations: m1DepositIndexer.computeConfirmations,
  ReceiptTallyMap: m1TallyMap.ReceiptTallyMap,
  computeRouteAmounts: m1Transition.computeRouteAmounts,
  computeBoundedSettlementAmounts: m1Transition.computeBoundedSettlementAmounts,
  computeSendRouteAmounts: m1Transition.computeSendRouteAmounts,
  applyBinarySettlementTransition: m1Transition.applyBinarySettlementTransition,
  TransitionCircuit: m1TransitionCircuit.TransitionCircuit,
  generateTransitionCircuit: m1TransitionCircuit.generateTransitionCircuit,
  toTransitionWitness: m1TransitionCircuit.toTransitionWitness,
  normalizeChallengeRoute: m1ChallengeWitness.normalizeRoute,
  buildTransitionStateFromChallengeBundle: m1ChallengeWitness.buildTransitionStateFromChallengeBundle,
  buildChallengeWitnessBundle: m1ChallengeWitness.buildChallengeWitnessBundle,
  buildOracleDeltaPublication: m1OracleDeltaPublication.buildOracleDeltaPublication,
  buildFastRollHandoff: m1OracleDeltaPublication.buildFastRollHandoff,
  deriveOracleMapId: m1OracleDeltaPublication.deriveOracleMapId,
  deriveNextContractId: m1OracleDeltaPublication.deriveNextContractId,
  buildSettlementBreakdown: m1WitnessDelta.buildSettlementBreakdown,
  buildSettlementDeltaAnnotation: m1WitnessDelta.buildSettlementDeltaAnnotation,
  buildWitnessBlobWithDelta: m1WitnessDelta.buildWitnessBlobWithDelta,
  CHAIN_PROFILES: m1ChainEnv.CHAIN_PROFILES,
  resolveChainId: m1ChainEnv.resolveChainId,
  resolveChainEnv: m1ChainEnv.resolveChainEnv,
  buildEpochEventId: m1ChainEnv.buildEpochEventId,
  normalizeRoutingCommitments: m1RoutingCommitments.normalizeRoutingCommitments,
  withCommittedRouting: m1RoutingCommitments.withCommittedRouting,
  assertCommittedRouting: m1RoutingCommitments.assertCommittedRouting,
  buildProceduralSyncSummary: m1ProceduralSync.buildProceduralSyncSummary,
  loadLatestProceduralSyncInputs: m1ProceduralSync.loadLatestProceduralSyncInputs,
  writeProceduralSyncSummary: m1ProceduralSync.writeProceduralSyncSummary,
  buildParallelUtxoIndex: m1ParallelUtxoIndex.buildParallelUtxoIndex,
  loadLatestParallelUtxoIndexInputs: m1ParallelUtxoIndex.loadLatestParallelUtxoIndexInputs,
  writeParallelUtxoIndex: m1ParallelUtxoIndex.writeParallelUtxoIndex,
  CONSTANT_ONE_DIGEST_HEX: m1BitvmSearchManifolds.CONSTANT_ONE_DIGEST_HEX,
  deriveSettlementCore: m1BitvmSearchManifolds.deriveSettlementCore,
  buildTranscriptMultiplicityFamily: m1BitvmSearchManifolds.buildTranscriptMultiplicityFamily,
  buildIdentifierBifurcationFamily: m1BitvmSearchManifolds.buildIdentifierBifurcationFamily,
  buildBitvmSearchManifolds: m1BitvmSearchManifolds.buildBitvmSearchManifolds,
  loadLatestBitvmSearchManifoldInputs: m1BitvmSearchManifolds.loadLatestBitvmSearchManifoldInputs,
  writeBitvmSearchManifolds: m1BitvmSearchManifolds.writeBitvmSearchManifolds,
  JURASSIC_BITVM_TARGETS: jurassicBitvmMechanisms.TARGETS,
  buildJurassicBitvmMechanismCore: jurassicBitvmMechanisms.buildMechanismCore,
  buildJurassicTranscriptSwitchboard: jurassicBitvmMechanisms.buildTranscriptSwitchboard,
  buildJurassicIdentifierRelayMatrix: jurassicBitvmMechanisms.buildIdentifierRelayMatrix,
  buildJurassicCarrierShadowRoutes: jurassicBitvmMechanisms.buildCarrierShadowRoutes,
  buildJurassicMechanismRefs: jurassicBitvmMechanisms.buildJurassicMechanismRefs,
  buildJurassicBitvmMechanismCatalog: jurassicBitvmMechanisms.buildJurassicBitvmMechanismCatalog,
  writeJurassicBitvmMechanismCatalog: jurassicBitvmMechanisms.writeJurassicBitvmMechanismCatalog,
  HALAL_CAPITAL_PROPERTY_TEMPLATES: halalCapitalTemplateRegistry.CAPITAL_PROPERTY_TEMPLATES,
  buildHalalCapitalTemplateRegistry: halalCapitalTemplateRegistry.buildCapitalTemplateRegistry,
  buildHalalCapitalCommitment: halalCapitalTemplateRegistry.buildCapitalCommitment,
  verifyHalalCapitalCommitment: halalCapitalTemplateRegistry.verifyCapitalCommitment,
  verifyExclusiveHalalCapitalSet: halalCapitalTemplateRegistry.verifyExclusiveCapitalSet,
  buildHalalCapitalRoleTransition: halalCapitalTemplateRegistry.buildCapitalRoleTransition,
  verifyHalalCapitalRoleTransition: halalCapitalTemplateRegistry.verifyCapitalRoleTransition,
  buildHalalCapitalRoadmap: halalCapitalTemplateRegistry.buildHalalCapitalRoadmap,
  writeHalalCapitalRoadmap: halalCapitalTemplateRegistry.writeHalalCapitalRoadmap,
  buildHalalCapitalMarketplaceSnapshot: halalCapitalMarketplaceDemo.buildHalalCapitalMarketplaceSnapshot,
  verifyHalalCapitalMarketplaceSnapshot: halalCapitalMarketplaceDemo.verifyHalalCapitalMarketplaceSnapshot,
  writeHalalCapitalMarketplaceSnapshot: halalCapitalMarketplaceDemo.writeHalalCapitalMarketplaceSnapshot,
  buildHalalCapitalObserverIndex: halalCapitalMarketplaceDemo.buildObserverIndex,
  buildHalalCapitalServiceRevenueEvent: halalCapitalMarketplaceDemo.buildServiceRevenueEvent,
  buildHalalCapitalTradeLayerTokenPlan: halalCapitalTradeLayerTokens.buildHalalCapitalTradeLayerTokenPlan,
  verifyHalalCapitalTradeLayerTokenPlan: halalCapitalTradeLayerTokens.verifyHalalCapitalTradeLayerTokenPlan,
  writeHalalCapitalTradeLayerTokenPlan: halalCapitalTradeLayerTokens.writeHalalCapitalTradeLayerTokenPlan,
  buildHalalCapitalTradeLayerTokenSpec: halalCapitalTradeLayerTokens.buildTradeLayerTokenSpec,
  buildHalalCapitalPrincipalMintEvent: halalCapitalTradeLayerTokens.buildPrincipalMintEvent,
  buildHalalCapitalServiceRevenueCreditEvent: halalCapitalTradeLayerTokens.buildServiceRevenueCreditEvent,
  HALAL_CAPITAL_PROTOCOL_PROPERTY_IDS: halalCapitalProtocolBundles.PROTOCOL_PROPERTY_IDS,
  buildHalalCapitalProtocolArtifact: halalCapitalProtocolBundles.buildProtocolArtifact,
  verifyHalalCapitalProtocolArtifact: halalCapitalProtocolBundles.verifyProtocolArtifact,
  buildHalalCapitalProtocolRetirementFlow: halalCapitalProtocolBundles.buildProtocolRetirementFlow,
  verifyHalalCapitalProtocolRetirementFlow: halalCapitalProtocolBundles.verifyProtocolRetirementFlow,
  buildHalalCapitalPropertyProtocolBundle: halalCapitalProtocolBundles.buildPropertyProtocolBundle,
  verifyHalalCapitalPropertyProtocolBundle: halalCapitalProtocolBundles.verifyPropertyProtocolBundle,
  buildHalalCapitalProtocolBundlePortfolio: halalCapitalProtocolBundles.buildHalalCapitalProtocolBundlePortfolio,
  verifyHalalCapitalProtocolBundlePortfolio: halalCapitalProtocolBundles.verifyHalalCapitalProtocolBundlePortfolio,
  writeHalalCapitalProtocolBundlePortfolio: halalCapitalProtocolBundles.writeHalalCapitalProtocolBundlePortfolio,
  buildOmaniFiqhStablecoinComplianceChecklist: omaniFiqhStablecoinCompliance.buildOmaniFiqhStablecoinComplianceChecklist,
  verifyOmaniFiqhStablecoinComplianceChecklist: omaniFiqhStablecoinCompliance.verifyOmaniFiqhStablecoinComplianceChecklist,
  writeOmaniFiqhStablecoinComplianceChecklist: omaniFiqhStablecoinCompliance.writeOmaniFiqhStablecoinComplianceChecklist,
  SUKUK_STABLECOIN_PROPERTY_ID: sukukStablecoinHalalDefi.STABLECOIN_PROPERTY_ID,
  SUKUK_STABLECOIN_TICKER: sukukStablecoinHalalDefi.STABLECOIN_TICKER,
  buildBankedSukukStablecoinReserve: sukukStablecoinHalalDefi.buildBankedSukukStablecoinReserve,
  verifyBankedSukukStablecoinReserve: sukukStablecoinHalalDefi.verifyBankedSukukStablecoinReserve,
  buildTradeLayerSukukStablecoinIssuance: sukukStablecoinHalalDefi.buildTradeLayerStablecoinIssuance,
  verifyTradeLayerSukukStablecoinIssuance: sukukStablecoinHalalDefi.verifyTradeLayerStablecoinIssuance,
  buildTaprootSukukStablecoinPledge: sukukStablecoinHalalDefi.buildTaprootStablecoinPledge,
  verifyTaprootSukukStablecoinPledge: sukukStablecoinHalalDefi.verifyTaprootStablecoinPledge,
  buildDynamicHawalaRouteQuote: sukukStablecoinHalalDefi.buildDynamicHawalaRouteQuote,
  verifyDynamicHawalaRouteQuote: sukukStablecoinHalalDefi.verifyDynamicHawalaRouteQuote,
  buildLightningHawalaRoutingMarket: sukukStablecoinHalalDefi.buildLightningHawalaRoutingMarket,
  verifyLightningHawalaRoutingMarket: sukukStablecoinHalalDefi.verifyLightningHawalaRoutingMarket,
  buildTradeLayerSukukArbMandate: sukukStablecoinHalalDefi.buildTradeLayerArbMandate,
  verifyTradeLayerSukukArbMandate: sukukStablecoinHalalDefi.verifyTradeLayerArbMandate,
  buildSukukStablecoinHalalDefiPortfolio: sukukStablecoinHalalDefi.buildSukukStablecoinHalalDefiPortfolio,
  verifySukukStablecoinHalalDefiPortfolio: sukukStablecoinHalalDefi.verifySukukStablecoinHalalDefiPortfolio,
  writeSukukStablecoinHalalDefiPortfolio: sukukStablecoinHalalDefi.writeSukukStablecoinHalalDefiPortfolio,
  deriveLightningPreimageHex: lightningIntegration.derivePreimageHex,
  deriveLightningPaymentHashHex: lightningIntegration.derivePaymentHashHex,
  makePrototypeLightningInvoice: lightningIntegration.makePrototypeInvoice,
  buildLightningFundingOutputCommitment: lightningIntegration.buildFundingOutputCommitment,
  buildLightningFundedPositionOpen: lightningIntegration.buildLightningFundedPositionOpen,
  buildLightningPayoutCompression: lightningIntegration.buildLightningPayoutCompression,
  verifyLightningPayoutCompression: lightningIntegration.verifyLightningPayoutCompression,
  buildLightningWatchtowerBounty: lightningIntegration.buildLightningWatchtowerBounty,
  buildContractOpenApiPrototype: lightningIntegration.buildContractOpenApiPrototype,
  buildLightningFundedRollover: lightningIntegration.buildLightningFundedRollover,
  buildAllLightningIntegrationPrototypes: lightningIntegration.buildAllLightningIntegrationPrototypes,
  SPIRAL_LDK_PUBLIC_COMMIT_EVIDENCE: spiralLdkValueAdd.PUBLIC_COMMIT_EVIDENCE,
  PUBLIC_COMMIT_EVIDENCE: spiralLdkValueAdd.PUBLIC_COMMIT_EVIDENCE,
  buildLdkExternalFundingReceipt: spiralLdkValueAdd.buildLdkExternalFundingReceipt,
  verifyLdkExternalFundingReceipt: spiralLdkValueAdd.verifyLdkExternalFundingReceipt,
  buildSpiralLdkValueAddBrief: spiralLdkValueAdd.buildSpiralLdkValueAddBrief,
  buildLiquidityLeaseOffer: lightningLiquidityLease.buildLiquidityLeaseOffer,
  buildLeaseSuccessEvidence: lightningLiquidityLease.buildLeaseSuccessEvidence,
  buildLeaseChallengeEvidence: lightningLiquidityLease.buildLeaseChallengeEvidence,
  buildLiquidityLeaseBundle: lightningLiquidityLease.buildLiquidityLeaseBundle,
  verifyLiquidityLeaseBundle: lightningLiquidityLease.verifyLiquidityLeaseBundle,
  buildWalletIntegrationManifest: lightningWalletIntegration.buildWalletIntegrationManifest,
  verifyWalletIntegrationManifest: lightningWalletIntegration.verifyWalletIntegrationManifest,
  buildTaprootAssetDescriptor: lightningTaprootAssetsStablecoin.buildTaprootAssetDescriptor,
  buildTaprootAssetProofCommitment: lightningTaprootAssetsStablecoin.buildTaprootAssetProofCommitment,
  buildStablecoinRfqQuote: lightningTaprootAssetsStablecoin.buildStablecoinRfqQuote,
  buildStablecoinSettlementEvidence: lightningTaprootAssetsStablecoin.buildStablecoinSettlementEvidence,
  buildStablecoinChallengeEvidence: lightningTaprootAssetsStablecoin.buildStablecoinChallengeEvidence,
  buildTaprootAssetsStablecoinBundle: lightningTaprootAssetsStablecoin.buildTaprootAssetsStablecoinBundle,
  verifyTaprootAssetsStablecoinBundle: lightningTaprootAssetsStablecoin.verifyTaprootAssetsStablecoinBundle,
  buildArkTemplateCommitment: lightningArkLiquidityGraft.buildArkTemplateCommitment,
  buildArkVtxoLiquidityCommitment: lightningArkLiquidityGraft.buildArkVtxoLiquidityCommitment,
  buildArkLiquidityGraftQuote: lightningArkLiquidityGraft.buildArkLiquidityGraftQuote,
  buildArkGraftSettlementEvidence: lightningArkLiquidityGraft.buildArkGraftSettlementEvidence,
  buildArkGraftChallengeEvidence: lightningArkLiquidityGraft.buildArkGraftChallengeEvidence,
  buildArkGraftCostModel: lightningArkLiquidityGraft.buildArkGraftCostModel,
  buildArkLiquidityGraftBundle: lightningArkLiquidityGraft.buildArkLiquidityGraftBundle,
  verifyArkLiquidityGraftBundle: lightningArkLiquidityGraft.verifyArkLiquidityGraftBundle,
  buildArkTaprootLeafSet: arkTaprootMiniscriptProofManifest.buildArkTaprootLeafSet,
  ARK_TAPROOT_MAX_PATH_DEPTH: arkTaprootMiniscriptProofManifest.MAX_TAPROOT_PATH_DEPTH,
  ARK_TAPROOT_PATH_ALGORITHM: arkTaprootMiniscriptProofManifest.TAPROOT_PATH_ALGORITHM,
  buildArkTaprootMiniscriptProofManifest:
    arkTaprootMiniscriptProofManifest.buildArkTaprootMiniscriptProofManifest,
  verifyArkTaprootMiniscriptProofManifest:
    arkTaprootMiniscriptProofManifest.verifyArkTaprootMiniscriptProofManifest,
  deriveArkTaprootLeafHash: arkTaprootMiniscriptProofManifest.deriveLeafHash,
  deriveArkTaprootBranchHash: arkTaprootMiniscriptProofManifest.deriveBranchHash,
  deriveArkTaprootPathProof: arkTaprootMiniscriptProofManifest.deriveTaprootPathProof,
  ARK_ZK_MINISCRIPT_ROLE_CODES: arkZkMiniscriptProof.ROLE_CODES,
  ARK_ZK_MINISCRIPT_ROLE_ORDER: arkZkMiniscriptProof.ROLE_ORDER,
  buildArkZkTaprootPathWitness: arkZkMiniscriptProof.buildTaprootPathWitness,
  splitArkZkHashToU128Limbs: arkZkMiniscriptProof.hex32ToU128Limbs,
  computeArkZkMiniscriptBinding: arkZkMiniscriptProof.computeArkZkMiniscriptBinding,
  buildArkZkMiniscriptClaim: arkZkMiniscriptProof.buildArkZkMiniscriptClaim,
  buildArkZkMiniscriptClaimCorpus: arkZkMiniscriptProof.buildArkZkMiniscriptClaimCorpus,
  writeArkZkMiniscriptClaimCorpus: arkZkMiniscriptProof.writeArkZkMiniscriptClaimCorpus,
  buildArkZkMiniscriptProofReceipt: arkZkMiniscriptProof.buildArkZkMiniscriptProofReceipt,
  verifyArkZkMiniscriptProofReceipt: arkZkMiniscriptProof.verifyArkZkMiniscriptProofReceipt,
  writeArkZkMiniscriptProofReceipt: arkZkMiniscriptProof.writeArkZkMiniscriptProofReceipt,
  writeArkZkMiniscriptProofReceiptsFromSummary:
    arkZkMiniscriptProof.writeArkZkMiniscriptProofReceiptsFromSummary,
  buildSyntheticLightningZkReceiptRef: lightningZkPrograms.buildSyntheticZkReceiptRef,
  buildLightningPaymentConditionProof: lightningZkPrograms.buildLightningPaymentConditionProof,
  verifyLightningPaymentConditionProof: lightningZkPrograms.verifyLightningPaymentConditionProof,
  buildArkZkReceiptRef: lightningZkPrograms.buildArkZkReceiptRef,
  buildProgrammableWatchtower: lightningZkPrograms.buildProgrammableWatchtower,
  verifyProgrammableWatchtower: lightningZkPrograms.verifyProgrammableWatchtower,
  buildProgrammableAspPolicy: lightningZkPrograms.buildProgrammableAspPolicy,
  verifyProgrammableAspPolicy: lightningZkPrograms.verifyProgrammableAspPolicy,
  buildProgrammableLightningZkBundle: lightningZkPrograms.buildProgrammableLightningZkBundle,
  verifyProgrammableLightningZkBundle: lightningZkPrograms.verifyProgrammableLightningZkBundle,
  writeProgrammableLightningZkBundle: lightningZkPrograms.writeProgrammableLightningZkBundle,
  buildShinigamiProgramState: shinigamiProofPublication.buildShinigamiProgramState,
  buildShinigamiProofPublication: shinigamiProofPublication.buildShinigamiProofPublication,
  buildShinigamiVerifierReceipt: shinigamiProofPublication.buildShinigamiVerifierReceipt,
  buildShinigamiProofChallenge: shinigamiProofPublication.buildShinigamiProofChallenge,
  buildShinigamiProofPublicationBundle: shinigamiProofPublication.buildShinigamiProofPublicationBundle,
  verifyShinigamiProofPublicationBundle: shinigamiProofPublication.verifyShinigamiProofPublicationBundle,
  buildShinigamiVirtualCetBundle: shinigamiVirtualCetArk.buildShinigamiVirtualCetBundle,
  verifyShinigamiVirtualCetBundle: shinigamiVirtualCetArk.verifyShinigamiVirtualCetBundle,
  buildShinigamiFraudCases: shinigamiVirtualCetArk.buildShinigamiFraudCases,
  buildShinigamiDashboardProof: shinigamiVirtualCetArk.buildShinigamiDashboardProof,
  writeShinigamiVirtualCetBundle: shinigamiVirtualCetArk.writeShinigamiVirtualCetBundle,
  buildShinigamiVirtualCetCairoClaim: shinigamiVirtualCetProofCorpus.buildShinigamiVirtualCetCairoClaim,
  buildShinigamiVirtualCetProofCorpus: shinigamiVirtualCetProofCorpus.buildShinigamiVirtualCetProofCorpus,
  writeShinigamiVirtualCetProofCorpus: shinigamiVirtualCetProofCorpus.writeShinigamiVirtualCetProofCorpus,
  buildShinigamiVirtualCetProofReceipt: shinigamiVirtualCetProofCorpus.buildShinigamiVirtualCetProofReceipt,
  verifyShinigamiVirtualCetProofReceipt: shinigamiVirtualCetProofCorpus.verifyShinigamiVirtualCetProofReceipt,
  writeShinigamiVirtualCetProofReceipts: shinigamiVirtualCetProofCorpus.writeShinigamiVirtualCetProofReceipts,
  buildDlcTokenizerSecurityComparison: dlcTokenizerSecurityComparison.buildDlcTokenizerSecurityComparison,
  verifyDlcTokenizerSecurityComparison: dlcTokenizerSecurityComparison.verifyDlcTokenizerSecurityComparison,
  writeDlcTokenizerSecurityComparison: dlcTokenizerSecurityComparison.writeDlcTokenizerSecurityComparison,
  buildAspReserveBond: aspBitvmReserveBond.buildAspReserveBond,
  buildAspObligationSet: aspBitvmReserveBond.buildAspObligationSet,
  buildAspMisbehaviorClaim: aspBitvmReserveBond.buildAspMisbehaviorClaim,
  buildAspReserveZkReceipt: aspBitvmReserveBond.buildAspReserveZkReceipt,
  buildBitvmReserveChallenge: aspBitvmReserveBond.buildBitvmReserveChallenge,
  buildAspBitvmReserveBundle: aspBitvmReserveBond.buildAspBitvmReserveBundle,
  verifyAspBitvmReserveBundle: aspBitvmReserveBond.verifyAspBitvmReserveBundle,
  buildAspReserveDashboardProof: aspBitvmReserveBond.buildAspReserveDashboardProof,
  writeAspBitvmReserveBundle: aspBitvmReserveBond.writeAspBitvmReserveBundle,
  buildArkDlcContract: arkDlcSettlement.buildArkDlcContract,
  buildVirtualCetSet: arkDlcSettlement.buildVirtualCetSet,
  buildArkDlcSettlement: arkDlcSettlement.buildArkDlcSettlement,
  buildArkDlcAspChallenge: arkDlcSettlement.buildArkDlcAspChallenge,
  buildArkDlcFeeModel: arkDlcSettlement.buildArkDlcFeeModel,
  buildArkDlcSettlementBundle: arkDlcSettlement.buildArkDlcSettlementBundle,
  verifyArkDlcSettlementBundle: arkDlcSettlement.verifyArkDlcSettlementBundle,
  buildArkLiquidityInventory: arkLiquidityGraftManager.buildArkLiquidityInventory,
  buildLightningRouteDemand: arkLiquidityGraftManager.buildLightningRouteDemand,
  buildBitvmEnforcementPolicy: arkLiquidityGraftManager.buildBitvmEnforcementPolicy,
  allocateArkGrafts: arkLiquidityGraftManager.allocateArkGrafts,
  buildArkLiquidityManagerChallenge: arkLiquidityGraftManager.buildArkLiquidityManagerChallenge,
  buildArkLiquidityGraftManagerBundle: arkLiquidityGraftManager.buildArkLiquidityGraftManagerBundle,
  verifyArkLiquidityGraftManagerBundle: arkLiquidityGraftManager.verifyArkLiquidityGraftManagerBundle,
  usdUnitsFromBtcSats: lnbtcTlusdLiquidityPatch.usdUnitsFromBtcSats,
  buildLnBtcToTlUsdConversion: lnbtcTlusdLiquidityPatch.buildLnBtcToTlUsdConversion,
  buildTlUsdLiquidityStake: lnbtcTlusdLiquidityPatch.buildTlUsdLiquidityStake,
  buildLiquidityPatchMandate: lnbtcTlusdLiquidityPatch.buildLiquidityPatchMandate,
  buildLnBtcTlUsdLiquidityPatchBundle: lnbtcTlusdLiquidityPatch.buildLnBtcTlUsdLiquidityPatchBundle,
  verifyLnBtcTlUsdLiquidityPatchBundle: lnbtcTlusdLiquidityPatch.verifyLnBtcTlUsdLiquidityPatchBundle,
  buildBitvmChannelInventory: bitvmChannelRouter.buildBitvmChannelInventory,
  buildBitvmChannelRouterPlan: bitvmChannelRouter.buildBitvmChannelRouterPlan,
  verifyBitvmChannelRouterPlan: bitvmChannelRouter.verifyBitvmChannelRouterPlan,
  buildBitvmChannelRouterWalletView: bitvmChannelRouter.buildBitvmChannelRouterWalletView,
  buildBitvmChannelRouterBundle: bitvmChannelRouter.buildBitvmChannelRouterBundle,
  verifyBitvmChannelRouterBundle: bitvmChannelRouter.verifyBitvmChannelRouterBundle,
  TRADELAYER_ORACLE_MAX_PRICE_DEVIATION_BPS: lightningTradeLayerOracleDlc.DEFAULT_MAX_PRICE_DEVIATION_BPS,
  TRADELAYER_DEFAULT_DESIGNATED_ORACLE_ADDRESS: lightningTradeLayerOracleDlc.DEFAULT_DESIGNATED_ORACLE_ADDRESS,
  encodeTradeLayerPublishOracleData: lightningTradeLayerOracleDlc.encodeTradeLayerPublishOracleData,
  decodeTradeLayerPublishOracleData: lightningTradeLayerOracleDlc.decodeTradeLayerPublishOracleData,
  buildTradeLayerOracleOpReturnScriptHex: lightningTradeLayerOracleDlc.buildOpReturnScriptHex,
  priceDeviationBps: lightningTradeLayerOracleDlc.priceDeviationBps,
  buildTradeLayerOracleAddressProof: lightningTradeLayerOracleDlc.buildOracleAddressProof,
  computeTradeLayerVwapScaledPrice: lightningTradeLayerOracleDlc.computeVwapScaledPrice,
  buildTradeLayerVwapStateOracle: lightningTradeLayerOracleDlc.buildTradeLayerVwapStateOracle,
  verifyTradeLayerVwapStateOracle: lightningTradeLayerOracleDlc.verifyTradeLayerVwapStateOracle,
  buildTradeLayerVwapStateOracleChallenge: lightningTradeLayerOracleDlc.buildTradeLayerVwapStateOracleChallenge,
  buildTradeLayerPricePublishTrigger: lightningTradeLayerOracleDlc.buildTradeLayerPricePublishTrigger,
  buildBilateralLnDlcContract: lightningTradeLayerOracleDlc.buildBilateralLnDlcContract,
  selectTradeLayerOracleDlcOutcomeForPrice: lightningTradeLayerOracleDlc.selectOutcomeForPrice,
  buildBitvmTradeLayerOracleDlcOrganizer: lightningTradeLayerOracleDlc.buildBitvmOrganizer,
  buildLnTradeLayerOracleDlcSettlement: lightningTradeLayerOracleDlc.buildLnDlcSettlement,
  buildBitvmTradeLayerOracleDlcChallenge: lightningTradeLayerOracleDlc.buildBitvmDlcChallenge,
  buildLightningTradeLayerOracleDlcBundle: lightningTradeLayerOracleDlc.buildLightningTradeLayerOracleDlcBundle,
  verifyLightningTradeLayerOracleDlcBundle: lightningTradeLayerOracleDlc.verifyLightningTradeLayerOracleDlcBundle,
  tradeLayerAddressToScriptPubKey: tradeLayerPnlRouteAdapter.addressToScriptPubKey,
  computeTradeLayerPnlPlanHash: tradeLayerPnlRouteAdapter.computeTradeLayerPlanHash,
  buildTradeLayerSendRouteTranscript: tradeLayerPnlRouteAdapter.buildTradeLayerSendRouteTranscript,
  verifyTradeLayerSendRouteTranscript: tradeLayerPnlRouteAdapter.verifyTradeLayerSendRouteTranscript,
  buildTradeLayerPnlCommitment: tradeLayerPnlRouteAdapter.buildTradeLayerPnlCommitment,
  verifyTradeLayerPnlRoutePlan: tradeLayerPnlRouteAdapter.verifyTradeLayerPnlRoutePlan,
  buildTradeLayerSendOracleCommitment: tradeLayerPnlRouteAdapter.buildTradeLayerSendOracleCommitment,
  buildTradeLayerSendOracleSigningPayload: tradeLayerPnlRouteAdapter.buildTradeLayerSendOracleSigningPayload,
  verifyTradeLayerSendOracleSignature: tradeLayerPnlRouteAdapter.verifyTradeLayerSendOracleSignature,
  buildTradeLayerSendIntentFromStateOracle: tradeLayerPnlRouteAdapter.buildTradeLayerSendIntentFromStateOracle,
  buildTradeLayerSendRoutePlan: tradeLayerPnlRouteAdapter.buildTradeLayerSendRoutePlan,
  verifyTradeLayerSendRoutePlan: tradeLayerPnlRouteAdapter.verifyTradeLayerSendRoutePlan,
  verifyTradeLayerSendStateOracleRoute: tradeLayerPnlRouteAdapter.verifyTradeLayerSendStateOracleRoute,
  buildTradeLayerPnlStateOracleCommitment: tradeLayerPnlStateNetting.buildTradeLayerPnlStateOracleCommitment,
  deriveTradeLayerPnlRowsFromStateOracle: tradeLayerPnlStateNetting.derivePnlRowsFromStateOracle,
  buildTradeLayerGrossPnlEdges: tradeLayerPnlStateNetting.buildGrossPnlEdges,
  computeTradeLayerPnlNetBalances: tradeLayerPnlStateNetting.computeNetBalances,
  foldTradeLayerPnlNettingGraph: tradeLayerPnlStateNetting.foldPnlNettingGraph,
  buildTradeLayerPnlNettingSettlement: tradeLayerPnlStateNetting.buildTradeLayerPnlNettingSettlement,
  verifyTradeLayerPnlNettingSettlement: tradeLayerPnlStateNetting.verifyTradeLayerPnlNettingSettlement,
  buildTradeLayerPnlNettingChallenge: tradeLayerPnlStateNetting.buildTradeLayerPnlNettingChallenge,
  verifyTradeLayerPnlNettingChallenge: tradeLayerPnlStateNetting.verifyTradeLayerPnlNettingChallenge,
  describeTradeLayerPnlNettingFlow: tradeLayerPnlStateNetting.describeTradeLayerPnlNettingFlow,
  buildTradeLayerSendStateOracleFromConsensus: tradeLayerSendOracleExtractor.buildTradeLayerSendStateOracleFromConsensus,
  buildTradeLayerSendSweepPlan: tradeLayerSendSweepPsbt.buildTradeLayerSendSweepPlan,
  verifyTradeLayerObservedSweepOutputs: tradeLayerSendSweepPsbt.verifyObservedSweepOutputs,
  TRADELAYER_SEND_FRAUD_CHALLENGE_TYPES: tradeLayerSendFraudChallenges.CHALLENGE_TYPES,
  buildTradeLayerSendFraudChallengeBundle: tradeLayerSendFraudChallenges.buildTradeLayerSendFraudChallengeBundle,
  verifyTradeLayerSendFraudChallengeBundle: tradeLayerSendFraudChallenges.verifyTradeLayerSendFraudChallengeBundle,
  buildTradeLayerSendWalletFlow: tradeLayerSendFlowModel.buildTradeLayerSendWalletFlow,
  verifyTradeLayerSendWalletFlow: tradeLayerSendFlowModel.verifyTradeLayerSendWalletFlow,
  TRADELAYER_SEND_DEFAULT_POLICY: tradeLayerSendPolicy.DEFAULT_POLICY,
  buildTradeLayerSendProductionPolicy: tradeLayerSendPolicy.buildTradeLayerSendProductionPolicy,
  verifyTradeLayerSendProductionPolicy: tradeLayerSendPolicy.verifyTradeLayerSendProductionPolicy,
  preflightTradeLayerSendRpcSweep: tradeLayerSendRpcSweep.preflightTradeLayerSendRpcSweep,
  executeTradeLayerSendRpcSweep: tradeLayerSendRpcSweep.executeTradeLayerSendRpcSweep,
  attachTradeLayerSendRpcSweepToPlan: tradeLayerSendRpcSweep.attachRpcSweepToSweepPlan,
  normalizeTradeLayerDecodedTxOutputs: tradeLayerSendRpcSweep.normalizeDecodedTxOutputs,
  computeTradeLayerDecodedTxOutputHash: tradeLayerSendRpcSweep.computeDecodedTxOutputHash,
  buildTradeLayerFinalSpendBinding: tradeLayerSendRpcSweep.buildFinalSpendBinding,
  buildTradeLayerSendWatchtowerReport: tradeLayerSendWatchtower.buildTradeLayerSendWatchtowerReport,
  verifyTradeLayerSendWatchtowerReport: tradeLayerSendWatchtower.verifyTradeLayerSendWatchtowerReport,
  buildTradeLayerStateCheckpoint: tradeLayerStateCheckpointReferee.buildTradeLayerStateCheckpoint,
  verifyTradeLayerStateCheckpoint: tradeLayerStateCheckpointReferee.verifyTradeLayerStateCheckpoint,
  buildTradeLayerCheckpointFraudProof: tradeLayerStateCheckpointReferee.buildTradeLayerCheckpointFraudProof,
  verifyTradeLayerCheckpointFraudProof: tradeLayerStateCheckpointReferee.verifyTradeLayerCheckpointFraudProof,
  buildTradeLayerWithdrawalQueue: tradeLayerWithdrawalQueueReferee.buildTradeLayerWithdrawalQueue,
  verifyTradeLayerWithdrawalQueue: tradeLayerWithdrawalQueueReferee.verifyTradeLayerWithdrawalQueue,
  buildTradeLayerWithdrawalQueueChallenge: tradeLayerWithdrawalQueueReferee.buildTradeLayerWithdrawalQueueChallenge,
  verifyTradeLayerWithdrawalQueueChallenge: tradeLayerWithdrawalQueueReferee.verifyTradeLayerWithdrawalQueueChallenge,
  TRADELAYER_WITHDRAWAL_PAYABLE_STATUSES: tradeLayerWithdrawalQueueReferee.PAYABLE_STATUSES,
  reservedSatsFromDepositSnapshot: tradeLayerReserveReconciliationReferee.reservedSatsFromDepositSnapshot,
  buildTradeLayerReserveReconciliation: tradeLayerReserveReconciliationReferee.buildTradeLayerReserveReconciliation,
  verifyTradeLayerReserveReconciliation: tradeLayerReserveReconciliationReferee.verifyTradeLayerReserveReconciliation,
  buildTradeLayerReserveInsolvencyChallenge: tradeLayerReserveReconciliationReferee.buildTradeLayerReserveInsolvencyChallenge,
  verifyTradeLayerReserveInsolvencyChallenge: tradeLayerReserveReconciliationReferee.verifyTradeLayerReserveInsolvencyChallenge,
  buildLiveReserveFromUnspent: tradeLayerLiveReserveAdapter.buildLiveReserveFromUnspent,
  liveReserveAmountSats: tradeLayerLiveReserveAdapter.toAmountSats,
  DLC_SETTLEMENT_OUTCOME_IDS: tradeLayerDlcCetOracleSelection.OUTCOME_IDS,
  buildDlcSettlementOutcomes: tradeLayerDlcCetOracleSelection.buildDlcSettlementOutcomes,
  buildDlcOracleAttestation: tradeLayerDlcCetOracleSelection.buildDlcOracleAttestation,
  verifyDlcOracleAttestation: tradeLayerDlcCetOracleSelection.verifyDlcOracleAttestation,
  selectCetForAttestation: tradeLayerDlcCetOracleSelection.selectCetForAttestation,
  RBTC_HOURLY_DLC_DURATION_SECONDS: tradeLayerRbtcHourlyAutoRoll.DEFAULT_DURATION_SECONDS,
  buildHourlyRbtcDlcContract: tradeLayerRbtcHourlyAutoRoll.buildHourlyRbtcDlcContract,
  buildRbtcBalanceOracleObservation: tradeLayerRbtcHourlyAutoRoll.buildBalanceOracleObservation,
  chooseRbtcAutoRollOutcomeFromBalance: tradeLayerRbtcHourlyAutoRoll.chooseOutcomeFromBalanceObservation,
  buildHourlyRbtcCetDecision: tradeLayerRbtcHourlyAutoRoll.buildHourlyRbtcCetDecision,
  TX30_RELAY_REFERENCE_PREFIX: tradeLayerTx30RelayAnchor.RELAY_REFERENCE_PREFIX,
  TX30_RELAY_MAX_OP_RETURN_PAYLOAD_BYTES: tradeLayerTx30RelayAnchor.MAX_STANDARD_OP_RETURN_PAYLOAD_BYTES,
  buildTx30RelayBlobEnvelope: tradeLayerTx30RelayAnchor.buildTx30RelayBlobEnvelope,
  buildTx30RelayReference: tradeLayerTx30RelayAnchor.buildTx30RelayReference,
  buildTx30RelayAnchor: tradeLayerTx30RelayAnchor.buildTx30RelayAnchor,
  verifyTx30RelayAnchor: tradeLayerTx30RelayAnchor.verifyTx30RelayAnchor,
  publishTx30RelayBundleToReplicas: tradeLayerTx30RelayRetrieval.publishRelayBundleToReplicas,
  retrieveTx30RelayBundleFromReplicas: tradeLayerTx30RelayRetrieval.retrieveRelayBundleFromReplicas,
  verifyTx30RelayBundleDocument: tradeLayerTx30RelayRetrieval.verifyRelayBundleDocument,
  buildTx30RelayRetrievalFault: tradeLayerTx30RelayRetrieval.buildRelayRetrievalFault,
  buildBetaKeySeparationCeremony: tradeLayerBetaGatePackage.buildKeySeparationCeremony,
  buildBetaOperationalDrillChecklist: tradeLayerBetaGatePackage.buildOperationalDrillChecklist,
  buildRealMoneyBetaGatePackage: tradeLayerBetaGatePackage.buildBetaGatePackage,
  dlcSchnorrSign: tradeLayerDlcAdaptorSig.schnorrSign,
  dlcSchnorrVerify: tradeLayerDlcAdaptorSig.schnorrVerify,
  dlcAdaptorSign: tradeLayerDlcAdaptorSig.adaptorSign,
  dlcAdaptorVerify: tradeLayerDlcAdaptorSig.adaptorVerify,
  dlcAdaptorComplete: tradeLayerDlcAdaptorSig.adaptorComplete,
  dlcAdaptorExtract: tradeLayerDlcAdaptorSig.adaptorExtract,
  buildDlcOracle: tradeLayerDlcAdaptorSig.buildDlcOracle,
  dlcOutcomePoint: tradeLayerDlcAdaptorSig.dlcOutcomePoint,
  dlcAttest: tradeLayerDlcAdaptorSig.dlcAttest,
  taprootOutputKey: tradeLayerTaproot.taprootOutputKey,
  taprootScriptPubKey: tradeLayerTaproot.taprootScriptPubKey,
  taprootTweakSecret: tradeLayerTaproot.taprootTweakSecret,
  bip341SighashDefault: tradeLayerTaproot.bip341SighashDefault,
  musig2KeyAgg: tradeLayerMusig2.keyAgg,
  musig2ApplyTweak: tradeLayerMusig2.applyTweak,
  musig2NonceAgg: tradeLayerMusig2.nonceAgg,
  musig2SessionValues: tradeLayerMusig2.sessionValues,
  musig2PartialSign: tradeLayerMusig2.partialSign,
  musig2PartialSigAgg: tradeLayerMusig2.partialSigAgg,
  musig2PartialSigAggAdaptor: tradeLayerMusig2.partialSigAggAdaptor,
  musig2AdaptorComplete: tradeLayerMusig2.adaptorCompleteMuSig,
  tapLeafHash: tradeLayerTaprootScript.tapLeafHash,
  taprootMerkleRoot: tradeLayerTaprootScript.merkleRoot,
  taprootTweakWithRoot: tradeLayerTaprootScript.taprootTweakWithRoot,
  taprootControlBlock: tradeLayerTaprootScript.controlBlock,
  taprootScriptPathSighash: tradeLayerTaprootScript.scriptPathSighash,
  TAPROOT_RESERVE_DEFAULT_RECOVERY_CSV_DELAY: taprootReserveVault.DEFAULT_RECOVERY_CSV_DELAY,
  TAPROOT_RESERVE_DEFAULT_RECOVERY_RISK_MARGIN_BLOCKS: taprootReserveVault.DEFAULT_RECOVERY_RISK_MARGIN_BLOCKS,
  buildTaprootReserveVaultManifest: taprootReserveVault.buildTaprootReserveVaultManifest,
  verifyTaprootReserveVaultManifest: taprootReserveVault.verifyTaprootReserveVaultManifest,
  verifyTaprootReserveVaultOnChain: taprootReserveVault.verifyTaprootReserveVaultOnChain,
  buildTaprootReserveVaultSet: taprootReserveVault.buildTaprootReserveVaultSet,
  buildTaprootReserveVaultSetFromRpc: taprootReserveVault.buildTaprootReserveVaultSetFromRpc,
  reservedSatsFromTaprootReserveVaultSet: taprootReserveVault.reservedSatsFromTaprootReserveVaultSet,
  buildTaprootReserveVaultSpendProposal: taprootReserveVault.buildVaultSpendProposal,
  approveTaprootReserveVaultSpend: taprootReserveVault.approveTaprootReserveVaultSpend,
  verifyTaprootReserveVaultGuardianApproval: taprootReserveVault.verifyGuardianApproval,
  buildBitCommitment: tradeLayerBitvmGadgets.buildBitCommitment,
  revealBit: tradeLayerBitvmGadgets.revealBit,
  buildEquivocationPunishmentScript: tradeLayerBitvmGadgets.buildEquivocationPunishmentScript,
  buildEquivocationWitness: tradeLayerBitvmGadgets.buildEquivocationWitness,
  BITVM_GATES: tradeLayerBitvmCircuit.GATES,
  buildBitvmWire: tradeLayerBitvmCircuit.buildWire,
  buildBitvmRevealScript: tradeLayerBitvmCircuit.buildRevealScript,
  bitvmGateInvalidRows: tradeLayerBitvmCircuit.gateInvalidRows,
  buildBitvmGateDisproveLeaves: tradeLayerBitvmCircuit.buildGateDisproveLeaves,
  findBitvmGateFraud: tradeLayerBitvmCircuit.findGateFraud,
  buildBitvmComparatorCircuit: tradeLayerBitvmComparator.buildComparatorCircuit,
  evaluateBitvmComparator: tradeLayerBitvmComparator.evaluateComparator,
  commitBitvmCircuitWires: tradeLayerBitvmComparator.commitCircuitWires,
  buildBitvmComparatorDisproveLeaves: tradeLayerBitvmComparator.buildComparatorDisproveLeaves,
  findBitvmComparatorFraud: tradeLayerBitvmComparator.findComparatorFraud,
  buildTaprootTree: tradeLayerTaprootTree.buildTaprootTree,
  taprootControlBlockWithPath: tradeLayerTaprootTree.controlBlockWithPath,
  buildBitvmTimeoutLeafScript: tradeLayerBitvmDispute.buildTimeoutLeafScript,
  buildBitvmDisputeTree: tradeLayerBitvmDispute.buildDisputeTree,
  bitvmCsvSequence: tradeLayerBitvmDispute.csvSequence,
  commitBitvmBoundWires: tradeLayerBitvmSolvencyReferee.commitBoundWires,
  buildBitvmInputBindingLeaves: tradeLayerBitvmSolvencyReferee.buildInputBindingLeaves,
  findBitvmInputFraud: tradeLayerBitvmSolvencyReferee.findInputFraud,
  buildBitvmSolvencyAssertTree: tradeLayerBitvmSolvencyReferee.buildSolvencyAssertTree,
  buildBitvmSha256Circuit: tradeLayerBitvmSha256.buildSha256Circuit,
  evaluateBitvmSha256: tradeLayerBitvmSha256.evaluateSha256,
  buildTradeLayerPerpPnlSettlement: tradeLayerPerpPnlReferee.buildTradeLayerPerpPnlSettlement,
  verifyTradeLayerPerpPnlSettlement: tradeLayerPerpPnlReferee.verifyTradeLayerPerpPnlSettlement,
  buildTradeLayerPerpPnlChallenge: tradeLayerPerpPnlReferee.buildTradeLayerPerpPnlChallenge,
  verifyTradeLayerPerpPnlChallenge: tradeLayerPerpPnlReferee.verifyTradeLayerPerpPnlChallenge,
  buildBitvmLiquidityLease: bitvmLiquidityLeaseReferee.buildBitvmLiquidityLease,
  verifyBitvmLiquidityLease: bitvmLiquidityLeaseReferee.verifyBitvmLiquidityLease,
  buildBitvmLiquidityLeaseChallenge: bitvmLiquidityLeaseReferee.buildBitvmLiquidityLeaseChallenge,
  verifyBitvmLiquidityLeaseChallenge: bitvmLiquidityLeaseReferee.verifyBitvmLiquidityLeaseChallenge,
  buildBitvmArenaSecurityReport: bitvmArenaSecurityReport.buildBitvmArenaSecurityReport,
  verifyBitvmArenaSecurityReport: bitvmArenaSecurityReport.verifyBitvmArenaSecurityReport,
  buildTradeLayerBitvmStackBundle: tradeLayerBitvmStack.buildTradeLayerBitvmStackBundle,
  verifyTradeLayerBitvmStackBundle: tradeLayerBitvmStack.verifyTradeLayerBitvmStackBundle,
  buildTradeLayerDashboardView: tradeLayerBitvmStack.buildDashboardView,
  tradeLayerDashboardJsonSchema: tradeLayerBitvmStack.dashboardJsonSchema,
  loadTradeLayerUtxoRefDecodedFinalTxFromRpc: tradeLayerUtxoRefLivePath.loadDecodedFinalTxFromRpc,
  buildTradeLayerUtxoRefDecodedFinalTx: tradeLayerUtxoRefLivePath.buildDecodedFinalTxFromSweepPlan,
  buildTradeLayerUtxoRefFinalOutputReview: tradeLayerUtxoRefLivePath.buildFinalOutputReview,
  buildTradeLayerUtxoRefFinalOutputChallenge: tradeLayerUtxoRefLivePath.buildFinalOutputChallenge,
  buildTradeLayerUtxoRefLivePathEvidence: tradeLayerUtxoRefLivePath.buildUtxoRefLivePathEvidence,
  verifyTradeLayerUtxoRefLivePathEvidence: tradeLayerUtxoRefLivePath.verifyUtxoRefLivePathEvidence,
  loadRbtcDlcZkSettlementBundle: rbtcDlcZkSettlementAdapter.loadRbtcDlcZkSettlementBundle,
  buildRbtcDlcBitvmSettlementReceipt: rbtcDlcZkSettlementAdapter.buildRbtcDlcBitvmSettlementReceipt,
  verifyRbtcDlcBitvmSettlementReceipt: rbtcDlcZkSettlementAdapter.verifyRbtcDlcBitvmSettlementReceipt,
  buildRbtcDlcBitvmChallenge: rbtcDlcZkSettlementAdapter.buildRbtcDlcBitvmChallenge,
  buildRbtcDlcBitvmChallengeResponse: rbtcDlcZkSettlementAdapter.buildRbtcDlcBitvmChallengeResponse,
  verifyRbtcDlcBitvmChallengeResponse: rbtcDlcZkSettlementAdapter.verifyRbtcDlcBitvmChallengeResponse,
  resolvePipelineOptions: m1Pipeline.resolvePipelineOptions,
  buildPipelinePlan: m1Pipeline.buildPipelinePlan,
  buildPipelineSummary: m1Pipeline.buildPipelineSummary,
  resolvePipelineValidationSkipReason: m1Pipeline.resolveValidationSkipReason,

  // Re-export submodules for advanced usage
  types,
  merkle,
  verify,
  circuit,
  m1Spec,
  m1ReceiptLedger,
  m1DepositIndexer,
  m1Transition,
  m1TransitionCircuit,
  m1TallyMap,
  m1ChallengeWitness,
  m1OracleDeltaPublication,
  m1WitnessDelta,
  m1ChainEnv,
  m1RoutingCommitments,
  m1ProceduralSync,
  m1Pipeline,
  m1ParallelUtxoIndex,
  m1BitvmSearchManifolds,
  jurassicBitvmMechanisms,
  halalCapitalTemplateRegistry,
  halalCapitalMarketplaceDemo,
  halalCapitalTradeLayerTokens,
  halalCapitalProtocolBundles,
  omaniFiqhStablecoinCompliance,
  sukukStablecoinHalalDefi,
  lightningIntegration,
  spiralLdkValueAdd,
  lightningLiquidityLease,
  lightningWalletIntegration,
  lightningTaprootAssetsStablecoin,
  lightningArkLiquidityGraft,
  arkTaprootMiniscriptProofManifest,
  arkZkMiniscriptProof,
  lightningZkPrograms,
  shinigamiProofPublication,
  shinigamiVirtualCetArk,
  shinigamiVirtualCetProofCorpus,
  dlcTokenizerSecurityComparison,
  aspBitvmReserveBond,
  arkDlcSettlement,
  arkLiquidityGraftManager,
  lnbtcTlusdLiquidityPatch,
  bitvmChannelRouter,
  lightningTradeLayerOracleDlc,
  tradeLayerPnlRouteAdapter,
  tradeLayerPnlStateNetting,
  tradeLayerSendOracleExtractor,
  tradeLayerSendSweepPsbt,
  tradeLayerSendFraudChallenges,
  tradeLayerSendFlowModel,
  tradeLayerSendPolicy,
  tradeLayerSendRpcSweep,
  tradeLayerSendWatchtower,
  tradeLayerStateCheckpointReferee,
  tradeLayerWithdrawalQueueReferee,
  tradeLayerReserveReconciliationReferee,
  tradeLayerLiveReserveAdapter,
  tradeLayerDlcCetOracleSelection,
  tradeLayerDlcAdaptorSig,
  tradeLayerTaproot,
  tradeLayerMusig2,
  tradeLayerTaprootScript,
  taprootReserveVault,
  tradeLayerTx30RelayAnchor,
  tradeLayerTx30RelayRetrieval,
  tradeLayerBetaGatePackage,
  tradeLayerBitvmGadgets,
  tradeLayerBitvmCircuit,
  tradeLayerBitvmComparator,
  tradeLayerTaprootTree,
  tradeLayerBitvmDispute,
  tradeLayerBitvmSolvencyReferee,
  tradeLayerBitvmSha256,
  tradeLayerPerpPnlReferee,
  bitvmLiquidityLeaseReferee,
  bitvmArenaSecurityReport,
  tradeLayerBitvmStack,
  tradeLayerUtxoRefLivePath,
  rbtcDlcZkSettlementAdapter
};

// The original sweep and BitVM demos remain importable from their source files
// for reproducibility, but they are not safe defaults. Package consumers must
// acknowledge that these APIs are prototype-only before loading them.
const LEGACY_UNSAFE_EXPORT_NAMES = Object.freeze([
  'CommitmentPackage',
  'PayoutLeaf',
  'PayoutOutput',
  'ResidualOutput',
  'SweepObject',
  'LEAF_TAG',
  'PayoutMerkleTree',
  'computeWithdrawalRoot',
  'buildTreeWithProofs',
  'ZERO_HASH',
  'verifySweep',
  'verifyRules',
  'deriveSettlementRouting',
  'verifySettlementRouting',
  'RefereeCircuit',
  'generateRefereeCircuit',
  'toCircuitWitness',
  'buildBitCommitment',
  'revealBit',
  'buildEquivocationPunishmentScript',
  'buildEquivocationWitness',
  'BITVM_GATES',
  'buildBitvmWire',
  'buildBitvmRevealScript',
  'bitvmGateInvalidRows',
  'buildBitvmGateDisproveLeaves',
  'findBitvmGateFraud',
  'buildBitvmComparatorCircuit',
  'evaluateBitvmComparator',
  'commitBitvmCircuitWires',
  'buildBitvmComparatorDisproveLeaves',
  'findBitvmComparatorFraud',
  'buildBitvmTimeoutLeafScript',
  'buildBitvmDisputeTree',
  'commitBitvmBoundWires',
  'buildBitvmInputBindingLeaves',
  'findBitvmInputFraud',
  'buildBitvmSolvencyAssertTree',
  'buildBitvmSha256Circuit',
  'evaluateBitvmSha256',
  'buildTradeLayerPerpPnlSettlement',
  'verifyTradeLayerPerpPnlSettlement',
  'buildTradeLayerPerpPnlChallenge',
  'verifyTradeLayerPerpPnlChallenge',
  'buildTradeLayerBitvmStackBundle',
  'verifyTradeLayerBitvmStackBundle',
  'buildTradeLayerDashboardView',
  'tradeLayerDashboardJsonSchema',
  'loadTradeLayerUtxoRefDecodedFinalTxFromRpc',
  'buildTradeLayerUtxoRefDecodedFinalTx',
  'buildTradeLayerUtxoRefFinalOutputReview',
  'buildTradeLayerUtxoRefFinalOutputChallenge',
  'buildTradeLayerUtxoRefLivePathEvidence',
  'verifyTradeLayerUtxoRefLivePathEvidence',
  'types',
  'merkle',
  'verify',
  'circuit',
  'tradeLayerWithdrawalQueueReferee',
  'tradeLayerBitvmGadgets',
  'tradeLayerBitvmCircuit',
  'tradeLayerBitvmComparator',
  'tradeLayerBitvmDispute',
  'tradeLayerBitvmSolvencyReferee',
  'tradeLayerBitvmSha256',
  'tradeLayerPerpPnlReferee',
  'tradeLayerBitvmStack',
  'tradeLayerUtxoRefLivePath',
  // MuSig2 is not on the pilot path. See legacy/.
  'musig2KeyAgg',
  'musig2ApplyTweak',
  'musig2NonceAgg',
  'musig2SessionValues',
  'musig2PartialSign',
  'musig2PartialSigAgg',
  'musig2PartialSigAggAdaptor',
  'musig2AdaptorComplete',
  'tradeLayerMusig2'
]);

// The sweep verifier (types, merkle, verify) was hardened on main against the
// 2026-09-11 red-team shape attacks and is scored by the locked
// eval/utxo_referee_eval.js through this entry point, so it stays importable
// at top level. It still verifies an abstract sweep object rather than a
// Bitcoin transaction; see PILOT_MERGE_NOTES.md.
const HARDENED_SWEEP_EXPORT_NAMES = new Set([
  'CommitmentPackage',
  'PayoutLeaf',
  'PayoutOutput',
  'ResidualOutput',
  'SweepObject',
  'LEAF_TAG',
  'PayoutMerkleTree',
  'computeWithdrawalRoot',
  'buildTreeWithProofs',
  'ZERO_HASH',
  'verifySweep',
  'verifyRules',
  'types',
  'merkle',
  'verify'
]);

const legacyUnsafeApi = {};
for (const name of LEGACY_UNSAFE_EXPORT_NAMES) {
  if (Object.prototype.hasOwnProperty.call(module.exports, name)) {
    legacyUnsafeApi[name] = module.exports[name];
    if (!HARDENED_SWEEP_EXPORT_NAMES.has(name)) delete module.exports[name];
  }
}
Object.freeze(legacyUnsafeApi);

const legacyUnsafe = Object.freeze({
  warning: 'UNSAFE V1 PROTOTYPES: self-authored roots, reusable proofs, public wire secrets, or key-path bypasses may be present.',
  exportNames: LEGACY_UNSAFE_EXPORT_NAMES,
  load(options = {}) {
    if (options.acknowledgeUnsafePrototype !== true) {
      throw new Error('legacyUnsafe requires acknowledgeUnsafePrototype: true');
    }
    return legacyUnsafeApi;
  }
});

module.exports.v2 = Object.freeze({
  settlement: utxoRefV2,
  trace: bitvmTraceV2,
  assertionGraph: bitvmAssertionGraphV2
});
module.exports.legacyUnsafe = legacyUnsafe;

// Experimental DLC infrastructure. Cryptographic signing remains disabled
// for production; these interfaces enforce transcript, threshold-oracle,
// and persistence gates on regtest and Bitcoin testnet4.
module.exports.dlc = Object.freeze({
  securityBoundaryVersion: 71,
  canonicalizeData: dlcCanonicalJson.canonicalize,
  canonicalJson: dlcCanonicalJson.canonicalJson,
  canonicalSerializationPolicy: Object.freeze({
    algorithm: 'utxoref-dlc-canonical-json-v2',
    sortedOwnStringKeys: true,
    plainObjectsAndArraysOnly: true,
    enumerableDataPropertiesOnly: true,
    accessorPropertiesAllowed: false,
    proxyObjectsAllowed: false,
    symbolPropertiesAllowed: false,
    sparseArraysAllowed: false,
    arrayExtraPropertiesAllowed: false,
    negativeZeroAllowed: false,
    ownProtoDataBound: true,
    inheritedToJsonHooksAllowed: false,
    containerEncoding: 'internal-recursive-json-v1',
    deeplyFrozenSnapshots: true,
    maxDepth: dlcCanonicalJson.MAX_CANONICAL_DEPTH,
    maxNodes: dlcCanonicalJson.MAX_CANONICAL_NODES,
    maxStringCodeUnits: dlcCanonicalJson.MAX_CANONICAL_STRING_CODE_UNITS,
    maxJsonBytes: dlcCanonicalJson.MAX_CANONICAL_JSON_BYTES
  }),
  contractInputPolicy: Object.freeze({
    recordsNormalizedBeforeFieldAccess: true,
    transitionRequestsNormalizedBeforeFieldAccess: true,
    receiptArgumentsDescriptorSnapshotted: true,
    callbackBearingInputsAllowed: false,
    durableReadsDeeplyFrozen: true,
    consumersUseCanonicalSnapshots: true,
    snapshotRetainedAcrossExternalCalls: true
  }),
  transactionSetInputPolicy: Object.freeze({
    constructionArgumentsDescriptorSnapshotted: true,
    bigIntAmountsSupported: true,
    normalizedBeforeFieldAccess: true,
    callbackBearingInputsAllowed: false,
    deeplyFrozenSnapshots: true,
    consumersUseCanonicalSnapshots: true,
    snapshotRetainedAcrossExternalCalls: true
  }),
  signerAuthorizationInputPolicy: Object.freeze({
    argumentsDescriptorSnapshotted: true,
    authorizationCanonicalSnapshot: true,
    adaptorPointBigIntSnapshot: true,
    callbackBearingInputsAllowed: false,
    snapshotRetainedThroughExecute: true
  }),
  providerConfigurationInputPolicy: Object.freeze({
    argumentsDescriptorSnapshotted: true,
    trustedAuditKeysCanonicalSnapshot: true,
    nativeClientIdentityCheckedBeforeProperties: true,
    nativeClientArgumentsDescriptorSnapshotted: true,
    nativeClientCapabilitiesCanonicalSnapshot: true,
    launchSpecCanonicalSnapshot: true,
    exactAuthorizationStoreIdentityRequired: true,
    proxiedStoresAllowed: false,
    callbackBearingInputsAllowed: false,
    providerStateImmutable: true
  }),
  signerProtocolInputPolicy: Object.freeze({
    authorizedRequestCanonicalSnapshot: true,
    requestSnapshottedBeforeRuntimeHash: true,
    responseArgumentsDescriptorSnapshotted: true,
    presignatureCanonicalSnapshot: true,
    consumptionArgumentsDescriptorSnapshotted: true,
    consumptionRecordsCanonicalSnapshot: true,
    callbackBearingInputsAllowed: false
  }),
  adaptorPrimitiveInputPolicy: Object.freeze({
    pointArgumentsDescriptorSnapshotted: true,
    boundedBigIntPointCoordinates: true,
    presignatureArgumentsDescriptorSnapshotted: true,
    presignatureOutputsFrozen: true,
    verificationFailsClosed: true,
    callbackBearingInputsAllowed: false
  }),
  oracleEnvelopeInputPolicy: Object.freeze({
    buildArgumentsDescriptorSnapshotted: true,
    outcomeBuffersCopied: true,
    maximumOutcomeCount: 256,
    announcementArgumentsDescriptorSnapshotted: true,
    announcementOutcomesCanonicalSnapshot: true,
    consumerSnapshotRetained: true,
    sealedStateArgumentsDescriptorSnapshotted: true,
    verificationFailsClosed: true,
    callbackBearingInputsAllowed: false
  }),
  createContract: dlcContractState.createDlcContract,
  normalizeContract: dlcContractState.normalizeDlcContract,
  validateContract: dlcContractState.validateDlcContract,
  transitionContract: dlcContractState.transitionDlcContract,
  requiredEvidence: dlcContractState.REQUIRED_EVIDENCE,
  StateStore: DlcStateStore,
  OracleEventStore: DlcOracleEventStore,
  SigningAuthorizationStore: DlcSigningAuthorizationStore,
  RefundRecoveryStore: DlcRefundRecoveryStore,
  BroadcastAuthorizationStore: DlcBroadcastAuthorizationStore,
  NativeSignerProcessClient: dlcNativeSignerProcessClient.DlcNativeSignerProcessClient,
  nativeSignerRuntimeDigest: dlcNativeSignerProcessClient.nativeSignerRuntimeDigest,
  validateOracleSet: dlcThresholdOracle.validateOracleSet,
  buildThresholdOutcomeSets: dlcThresholdOracle.buildThresholdOutcomeSets,
  combineThresholdAttestations: dlcThresholdOracle.combineThresholdAttestations,
  createCryptoProvider: dlcCryptoProvider.createDlcCryptoProvider,
  requireSigningProvider: dlcCryptoProvider.requireDlcSigningProvider,
  createAdaptorSignAuthorization: dlcCryptoProvider.createDlcAdaptorSignAuthorization,
  authorizeAdaptorSign: dlcCryptoProvider.authorizeDlcAdaptorSign,
  parseCanonicalUnsignedTransaction: dlcTransactionValidator.parseCanonicalUnsignedTransaction,
  parseCanonicalSignedTaprootTransaction: dlcTransactionValidator.parseCanonicalSignedTaprootTransaction,
  validateTransactionSet: dlcTransactionValidator.validateDlcTransactionSet,
  normalizeTransactionSet: dlcTransactionValidator.normalizeDlcTransactionSet,
  validateTransactionSetCommitments: dlcTransactionValidator.validateDlcTransactionSetCommitments,
  validateFundingPrebroadcastPolicy: dlcFundingPrebroadcastGuard.validateFundingPrebroadcastPolicy,
  validateExecutionPrebroadcastPolicy: dlcExecutionPrebroadcastGuard.validateExecutionPrebroadcastPolicy,
  trucPolicy: Object.freeze({
    strategy: 'truc-p2a-v1',
    transactionVersion: dlcTransactionValidator.TRUC_VERSION,
    p2aScriptPubKeyHex: dlcTransactionValidator.P2A_SCRIPT_PUBKEY_HEX,
    maxSettlementVsize: dlcTransactionValidator.TRUC_MAX_VSIZE,
    maxRecoveryVsize: dlcTransactionValidator.TRUC_CHILD_MAX_VSIZE,
    maxUnconfirmedClusterTransactions: dlcTransactionValidator.TRUC_MAX_UNCONFIRMED_CLUSTER_TRANSACTIONS
  }),
  recoveryPolicy: Object.freeze({
    proposalPolicyRpc: 'testmempoolaccept',
    exactTxidAndWtxid: true,
    stableMempoolSequence: true,
    failClosedOnCoreRejection: true
  }),
  fundingPrebroadcastPolicy: Object.freeze({
    receiptKind: 'prebroadcast_bitcoin_core_policy',
    policyRpc: 'testmempoolaccept',
    decodeRpc: 'decoderawtransaction',
    exactTxidAndWtxid: true,
    stableTipAndMempoolSequence: true,
    contractAndApprovedPsbtBound: true,
    signingAllowed: false,
    sendRawTransactionAllowed: false
  }),
  executionPrebroadcastPolicy: Object.freeze({
    receiptKinds: Object.freeze([
      'cet_prebroadcast_bitcoin_core_policy',
      'refund_prebroadcast_bitcoin_core_policy'
    ]),
    executionTypes: dlcExecutionPrebroadcastGuard.EXECUTION_TYPES,
    policyRpc: 'testmempoolaccept',
    decodeRpc: 'decoderawtransaction',
    exactTxidAndWtxid: true,
    committedSettlementBound: true,
    executionEvidenceBound: true,
    stableTipAndMempoolSequence: true,
    signingAllowed: false,
    sendRawTransactionAllowed: false
  }),
  broadcastAuthorizationPolicy: Object.freeze({
    maxPolicyTtlSeconds: 30,
    defaultPolicyTtlSeconds: 15,
    maxFutureClockSkewSeconds: 5,
    durableConsumeBeforeBroadcast: true,
    crossProcessSingleConsumer: true,
    transactionBytesRehashedAtConsumption: true,
    transitionSignaturesRevalidatedAtConsumption: true,
    linkedConsumptionRecordsAllowed: false,
    sharedDurableRecordPrimitive: true,
    consumptionParentIdentityBound: true,
    atomicNoReplacePublication: true,
    signingAllowed: false,
    sendRawTransactionAllowed: false,
    raceWorkers: 16,
    exactOneRaceWinner: true
  }),
  durableJournalPolicy: Object.freeze({
    recordReadProtocol: 'lstat-open-fstat-lstat-v2',
    atomicNoReplacePublication: 'link-excl-then-unlink-v1',
    contractStateDirectoryKey: 'sha256-contract-id-v1',
    nonSymlinkDirectoriesRequired: true,
    linkedFinalRecordsAllowed: false,
    identityStableThroughReadRequired: true,
    pathEntryStableThroughReadRequired: true,
    pathEntryStableThroughFinalFlushRequired: true,
    directoryLinkTraversalAllowed: false,
    exactSequenceFilenamesRequired: true,
    externalCheckpointKind: 'utxoref_dlc_journal_checkpoint_v1',
    signedExternalCheckpointKind: 'utxoref_dlc_signed_journal_checkpoint_v1',
    signedCheckpointAlgorithm: 'ed25519',
    signedCheckpointSignerKeyId: 'sha256-spki-der-v1',
    trustedCheckpointKeysPinned: true,
    signedCheckpointRequiredForUntrustedStorage: true,
    unsignedCheckpointStorageRequiresIndependentIntegrity: true,
    verifySignedCheckpointOnAllStores: true,
    signedCheckpointEnvelopeHash: 'sha256-canonical-envelope-v1',
    signedCheckpointExpectedHashRequired: true,
    signedCheckpointReplayProtection: 'caller-held-envelope-hash-v1',
    signedCheckpointPinInsideUntrustedStorageAllowed: false,
    checkpointStores: Object.freeze([
      'contract-state', 'oracle-event', 'peer-session', 'signing-authorization',
      'refund-recovery', 'broadcast-authorization', 'watchtower'
    ]),
    checkpointBindsRecordAtPinnedCount: true,
    longerHistoryMustContainPinnedHead: true,
    checkpointStorageInsideJournalAllowed: false,
    checkpointInputsNormalizedToFrozenPlainData: true,
    readBuffersCleared: true,
    temporaryRecordFsynced: true,
    finalRecordFsynced: true,
    recursiveLockCleanupAllowed: false,
    maxRecordBytes: Object.freeze({
      contractState: 4194304,
      oracleEvent: 1048576,
      peerSession: 131072,
      watchtowerObservation: 4194304
    })
  }),
  testnet4EvaluationPolicy: Object.freeze({
    stableSnapshotProtocol: 'tip-mempool-wallet-outpoints-v1',
    bestBlockHashBracketed: true,
    mempoolSequenceBracketed: true,
    getTxOutTipBound: true,
    walletLastProcessedBlockRequired: true,
    walletScanningRejected: true,
    deterministicUtxoOrdering: true,
    sameHeightForkDistinctEpoch: true,
    callerOwnedProtocolBuffersCopied: true,
    trustedCommitmentsImmutable: true,
    trustedPayoutLeavesImmutable: true,
    exportedHashConstantsDetached: true,
    merkleRootsAndProofsCopiedOnRead: true,
    hostAclPreflightRequiredForUntrustedAgents: true,
    bitcoinCoreBinaryProvenance: 'authenticode-sha256-v1',
    bitcoinCoreSignerThumbprint: '3A31CC9595E7A30096A8EA77F9DA2A6CB63F766F',
    bitcoinCoreDaemonSha256: 'f79eeb94e1379986df9f7be4c78c8fc8e18dc9be64a31cbaa8acad249d3db77a',
    bitcoinCoreCliSha256: 'f6ff1c850fd812c88afd817daac488dfac48b1a12eb99090ce541a663787698b',
    actualRpcListenerLoopbackRequired: true,
    rpcListenerOwnerBinaryPinned: true,
    evidenceRequiresCleanWorktree: true,
    compatibilitySnapshotDirtyTreeAllowed: false,
    scaleSnapshotDirtyTreeAllowed: false,
    evidenceCommitMustRemainStable: true,
    dedicatedSwarmAccountRequired: true,
    swarmAccountMustDifferFromCoordinator: true,
    swarmAccountAdministratorAllowed: false,
    proxyTokenAclRequired: true,
    proxyTokenParentAclRequired: true,
    proxyTokenWritableBySwarmAllowed: false,
    proxyTokenParentWritableBySwarmAllowed: false,
    untrustedAgentWalletPrivateKeysAllowed: false,
    watchOnlySwarmWalletRequired: true,
    watchOnlyWalletProvisioning: 'public-descriptor-import-v1',
    privateDescriptorsAccepted: false,
    exactWatchOnlyUtxoParityRequired: true,
    sourceWalletModified: false,
    watchOnlyEvidenceLiveRevalidated: true,
    watchOnlyEvidenceFileTrusted: false,
    watchOnlyAuditMutationAllowed: false,
    watchOnlyProvisioningSigningAllowed: false,
    watchOnlyProvisioningBroadcastAllowed: false,
    broadcastDefault: false,
    readonlyRpcProxy: 'loopback-capability-firewall-v1',
    readonlyRpcMethods: Object.freeze([
      'decoderawtransaction', 'getbestblockhash', 'getblockchaininfo', 'getblockhash',
      'getblockheader', 'getnetworkinfo', 'getrawmempool', 'gettxout', 'testmempoolaccept'
    ]),
    readonlyRpcMaxConcurrentRequests: 4,
    readonlyRpcMaxAuthenticatedRequestsPerMinute: 120,
    readonlyRpcMaxConnections: 16,
    readonlyRpcTokenFormat: 'lowercase-hex-256-bit',
    readonlyRpcTokenRevalidatedPerRequest: true,
    readonlyRpcTokenRotationRevokesImmediately: true,
    readonlyRpcTokenComparisonBuffersCleared: true,
    readonlyRpcCredentialReadIdentityBound: true,
    readonlyRpcCredentialHardLinksAllowed: false,
    readonlyRpcCredentialReadBuffersCleared: true,
    readonlyRpcMaxRequestBytes: 1048576,
    readonlyRpcMaxResponseBytes: 4194304,
    walletRpcAllowedThroughProxy: false,
    signingRpcAllowedThroughProxy: false,
    broadcastRpcAllowedThroughProxy: false,
    nodeControlRpcAllowedThroughProxy: false,
    networkControlRpcAllowedThroughProxy: false
  }),
  signerPolicy: Object.freeze({
    nativeCapabilityAttestation: 'ed25519',
    operatorPinnedAuditKeys: true,
    binaryDigestBound: true,
    auditDigestBound: true,
    contractTranscriptBound: true,
    processOneShotAdaptorAuthorization: true,
    durableAuthorizationStore: true,
    consumeBeforeSign: true,
    crossProcessSingleConsumer: true,
    signingConsumptionIdentityBound: true,
    signingConsumptionParentIdentityBound: true,
    signingConsumptionHardLinksAllowed: false,
    signingConsumptionReadBuffersCleared: true,
    signingConsumptionFinalRecordFsynced: true,
    signingConsumptionAtomicNoReplacePublication: true,
    signingConsumptionMaxRecordBytes: 32768,
    fullySignedRefundRecoveryRequired: true,
    refundRecoveryAppendOnce: true,
    refundRecoveryTaprootWitnessVerified: true,
    refundRecoveryRestoredBeforeFunding: true,
    refundRecoveryReceiptDigestBound: true,
    refundRecoverySharedDurableRecordPrimitive: true,
    refundRecoveryParentIdentityBound: true,
    refundRecoveryReadBuffersCleared: true,
    refundRecoveryAtomicNoReplacePublication: true,
    refundRecoveryRaceWorkers: 16,
    exactOneRefundArtifactRaceWinner: true,
    rawAdaptorSignHidden: true,
    nativeSigningRequestKind: 'utxoref_dlc_native_adaptor_sign_request_v1',
    callerSuppliesNativeSecret: false,
    nativeKeySelection: 'authorized-xonly-pubkey',
    nativeVerifiesAuthorization: true,
    hostSecretInputRejected: true,
    enforcedProcessClient: true,
    runtimeClosureRehashedPerRequest: true,
    runtimeClosureRegularFilesOnly: true,
    runtimeClosureRejectsLinkedPaths: true,
    runtimeClosureRejectsHardLinks: true,
    runtimeClosureIdentityBoundReads: 'lstat-open-fstat-lstat-v1',
    runtimeClosureParentIdentityBound: true,
    runtimeClosureReadBuffersCleared: true,
    runtimeClosureCheckedAfterExecution: true,
    maxAuditedExecutableBytes: 134217728,
    maxAuditedCodeFileBytes: 16777216,
    challengeBoundRuntimeIdentity: true,
    boundedProcessIoAndTimeout: true,
    sanitizedProcessEnvironment: true,
    nativeCandidateImplementation: 'rust-k256-v1',
    nativeCandidateProtocol: 'utxoref-dlc-native-signer-process-v2',
    nativeCandidateBinarySha256: '2f0c80cb80229c516d756c8e4f3f9fdb5d4d6c910aadc5c96844cb783b29033b',
    nativeCandidateCargoLockSha256: 'a5715dcfcf1eef714ffb08afe6b35fdd5db6278176ead3994286da12ba01c5e2',
    lockedDirectDependencies: true,
    unsafeRustRestrictedToDpapiFfi: true,
    unsafeDpapiFfiBlocks: 7,
    reproducibleWindowsBuild: true,
    crossLanguageAdaptorVerification: true,
    signerLocalDurableReplayStore: true,
    validatorPolicyClosureBound: true,
    signerKeyPolicyClosureBound: true,
    secretIntermediatesZeroizeOnDrop: true,
    directSignerReplayRaceWorkers: 16,
    exactOneDirectSignerRaceWinner: true,
    adaptorAuthorizationKind: 'utxoref_dlc_adaptor_sign_authorization_v3',
    maxAdaptorAuthorizationTtlSeconds: 300,
    maxAdaptorAuthorizationClockSkewSeconds: 30,
    nativeAuthorizationFreshnessVerified: true,
    trustedWallClockRequired: true,
    runtimeIdentitySignedClockFloor: true,
    maxSignedClockObservations: 4096,
    clockRollbackFailsBeforeKeyUse: true,
    crossProcessClockStoreLock: 'windows-file-lock-v1',
    clockStoreLockTimeoutMs: 20000,
    parallelDistinctAuthorizationsTested: 16,
    freshnessCheckedBeforeAuthorizationConsumption: true,
    keyStorageBackend: 'windows-dpapi-current-user-v1',
    plaintextKeyFilesRejected: true,
    pinnedDpapiAccessVerifier: true,
    dedicatedSignerAccountRequired: true,
    expectedWindowsAccountSidBound: true,
    protectedKeyDirectoryAclRequired: true,
    allowedKeyDirectoryPrincipals: Object.freeze(['signer-account', 'SYSTEM', 'Administrators']),
    nativeDpapiDecryption: true,
    decryptionSecretIpcEliminated: true,
    dpapiAccessVerifierOutput: 'none',
    dpapiOutputMemoryLocked: true,
    decryptedKeyBufferMemoryLocked: true,
    memoryLockFailureFailsClosed: true,
    processMitigationsApplied: true,
    system32OnlyDllSearch: true,
    dynamicCodeProhibited: true,
    microsoftSignedImagesOnly: true,
    extensionPointsDisabled: true,
    remoteAndLowIntegrityImagesRejected: true,
    selfVerifiedExecutableDigest: true,
    signerAccountKeyGeneration: 'in-account-windows-csprng-dpapi-v1',
    provisioningSecretIpcEliminated: true,
    signerTransport: 'windows-named-pipe-broker-v1',
    pipeRequestMaxBytes: 65536,
    pipeResponseMaxBytes: 1048576,
    pipeBrokerPrivateKeyAccess: false,
    pipeTransportDescriptorAttested: true,
    unauthorizedPipeClientsRejected: true,
    runtimeSignedPipeResponses: true,
    rustSecAuditRequired: true,
    rustSecVulnerabilitiesAllowed: 0,
    rustSecWarningsAllowed: 0,
    dependencyAuditEvidenceBound: true,
    externalAuditRequired: true,
    productionReady: false
  }),
  bitAgentCriticalSurface: Object.freeze({
    manifest: 'utxoref-bitagent-critical-surface-v2',
    dependencyDiscovery: 'static-commonjs-relative-require-v1',
    entryPoints: Object.freeze(['index.js', 'taproot_reserve_vault.js']),
    normalizedTextLineEndings: 'lf',
    regularFilesOnly: true,
    maxFileBytes: 4194304
  }),
  validateCetAdaptorSignatures: dlcSignatureValidator.validateCetAdaptorSignatures,
  validateRefundSignature: dlcSignatureValidator.validateRefundSignature,
  evaluateChainSnapshot: dlcChainGuard.evaluateDlcChainSnapshot,
  captureBitcoinCoreSnapshot: dlcBitcoinCoreObserver.captureDlcChainSnapshot,
  captureBitcoinCoreAnchorSnapshot: dlcBitcoinCoreObserver.captureDlcAnchorRecoverySnapshot,
  observeBitcoinCoreChain: dlcBitcoinCoreObserver.observeAndEvaluateDlcChain,
  peerMessageTypes: dlcPeerTranscript.TYPES,
  testnet4ChainHash: dlcPeerTranscript.TESTNET4_CHAIN_HASH,
  computeOraclePolicyDigest: dlcPeerTranscript.computeOraclePolicyDigest,
  computeContractId: dlcPeerTranscript.computeDlcContractId,
  signPeerMessage: dlcPeerTranscript.signDlcPeerMessage,
  verifyPeerMessage: dlcPeerTranscript.verifyDlcPeerMessage,
  validatePeerTranscript: dlcPeerTranscript.validateDlcPeerTranscript,
  PeerSessionStore: DlcPeerSessionStore,
  WatchtowerJournal: DlcWatchtowerJournal,
  createJournalCheckpoint: dlcJournalCheckpoint.createDlcJournalCheckpoint,
  normalizeJournalCheckpoint: dlcJournalCheckpoint.normalizeDlcJournalCheckpoint,
  validateJournalCheckpoint: dlcJournalCheckpoint.validateDlcJournalCheckpoint,
  signJournalCheckpoint: dlcJournalCheckpoint.signDlcJournalCheckpoint,
  normalizeSignedJournalCheckpoint: dlcJournalCheckpoint.normalizeSignedDlcJournalCheckpoint,
  signedJournalCheckpointHash: dlcJournalCheckpoint.signedDlcJournalCheckpointHash,
  verifySignedJournalCheckpoint: dlcJournalCheckpoint.verifySignedDlcJournalCheckpoint,
  settlementAnchor: dlcAnchorRecoveryGuard.settlementAnchor,
  evaluateAnchorRecovery: dlcAnchorRecoveryGuard.evaluateDlcAnchorRecovery
});
